{% set name = "gql" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 259b0c66d8dfe61feb06fe45b57713da0fe2e5ca13fa500a1fafc9bf2f195e81

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six >=1.10.0
    - graphql-core >=2,<3
    - promise >=2.0,<3
    - requests >=2.12,<3

test:
  imports:
    - gql
    - gql.transport

about:
  home: https://github.com/graphql-python/gql
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: GraphQL client for Python
  description: This is a GraphQL client for Python. Plays nicely with graphene, graphql-core, graphql-js andany other GraphQL implementation compatible with the spec.
extra:
  recipe-maintainers:
    - ozagordi
    - KingDarBoja
