{% set name = "gql" %}
{% set version = 0.2.0 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ad0f0b8226428d727c8e1d1cac4e521d83ed024d814921bd55b8adb997dadf4b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - graphql-core >=0.5.0,<2
    - python
    - promise >=2.0,<3
    - requests >=2.12,<3
    - six >=1.10.0

test:
  imports:
    - gql
    - gql.transport
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/graphql-python/gql
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: GraphQL client for Python
  description: This is a GraphQL client for Python. Plays nicely with graphene, graphql-core, graphql-js and any other GraphQL implementation compatible with the spec.
extra:
  recipe-maintainers:
    - ozagordi
    - KingDarBoja
