{% set name = "gql" %}
{% set version = "3.5.0" %}

package:
  name: gql-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ccb9c5db543682b28f577069950488218ed65d4ac70bb03b6929aaadaf636de9

build:
  number: 0
  skip: true  # [py<36 or s390x]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python

outputs:
  - name: gql
    build:
      script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
      entry_points:
        - gql-cli=gql.cli:gql_cli
    requirements:
      host:
        - python
        - pip
        - wheel
        - setuptools
      run:
        - python
        - graphql-core >=3.2,<3.3
        - yarl >=1.6,<2.0
        - backoff >=1.11.1,<3.0
        - anyio >=3.0,<5
      run_constrained:
        # aiohttp
        - aiohttp >=3.8.0,<4  # [py<=311]
        - aiohttp >=3.9.0,<4  # [py>311]
        # httpx
        - httpx >=0.23.1,<1
        # requests
        - requests >=2.26,<3
        - requests-toolbelt >=1.0.0,<2
        - urllib3 >=1.26
        # websockets
        - websockets >=10,<12
        # boto
        - botocore >=1.21,<2
    test:
      imports:
        - gql
      requires:
        - pip
      commands:
        - pip check
        - gql-cli --help
        - gql-cli --version

  - name: gql-with-aiohttp
    build:
    requirements:
      host:
        - python
        - pip
        - wheel
        - setuptools
      run:
        - {{ pin_subpackage('gql', exact=True) }}
        - aiohttp >=3.8.0,<4  # [py<=311]
        - aiohttp >=3.9.0,<4  # [py>311]
        - python
    test:
      imports:
        - gql
        - gql.transport.aiohttp
      requires:
        - pip
      commands:
        - pip check
        - gql-cli --help
        - gql-cli --version
    about:
      summary: GraphQL client for Python - aiohttp transport

  - name: gql-with-httpx
    build:
    requirements:
      host:
        - python
        - pip
        - wheel
        - setuptools
      run:
        - {{ pin_subpackage('gql', exact=True) }}
        - python
        - httpx >=0.23.1,<1
    test:
      imports:
        - gql
        - gql.transport.httpx
      requires:
        - pip
      commands:
        - pip check
        - gql-cli --help
        - gql-cli --version
    about:
      summary: GraphQL client for Python - httpx transport

  - name: gql-with-requests
    build:
    requirements:
      host:
        - python
        - pip
        - wheel
        - setuptools
      run:
        - {{ pin_subpackage('gql', exact=True) }}
        - python
        - requests >=2.26,<3
        - requests-toolbelt >=1.0.0,<2
        - urllib3 >=1.26
    test:
      imports:
        - gql
        - gql.transport.requests
      requires:
        - pip
      commands:
        - pip check
        - gql-cli --help
        - gql-cli --version
    about:
      summary: GraphQL client for Python - requests transport

  - name: gql-with-websockets
    build:
    requirements:
      host:
        - python
        - pip
        - wheel
        - setuptools
      run:
        - {{ pin_subpackage('gql', exact=True) }}
        - python
        - websockets >=10,<12
    test:
      imports:
        - gql
        - gql.transport.websockets
      requires:
        - pip
      commands:
        - pip check
        - gql-cli --help
        - gql-cli --version
    about:
      summary: GraphQL client for Python - websocket transport

  - name: gql-with-botocore
    build:
    requirements:
      host:
        - python
        - pip
        - wheel
        - setuptools
      run:
        - {{ pin_subpackage('gql', exact=True) }}
        - botocore >=1.21,<2
        - python
    test:
      imports:
        - gql
        - gql.transport.appsync_auth
      requires:
        - pip
      commands:
        - pip check
        - gql-cli --help
        - gql-cli --version
    about:
      summary: GraphQL client for Python - boto transport

  - name: gql-with-all
    build:
    requirements:
      host:
        - python
        - pip
        - wheel
        - setuptools
      run:
        - {{ pin_subpackage('gql-with-aiohttp', exact=True) }}
        - {{ pin_subpackage('gql-with-httpx', exact=True) }}
        - {{ pin_subpackage('gql-with-botocore', exact=True) }}
        - {{ pin_subpackage('gql-with-requests', exact=True) }}
        - {{ pin_subpackage('gql-with-websockets', exact=True) }}
        - {{ pin_subpackage('gql', exact=True) }}
        - python
    test:
      imports:
        - gql
        - gql.transport.httpx
        - gql.transport.aiohttp
        - gql.transport.requests
        - gql.transport.appsync_auth
        - gql.transport.websockets
      source_files:
        - tests
      requires:
        - aiofiles
        - mock
        - parse
        - pip
        - pytest
        - pytest-asyncio
        - pytest-console-scripts
        - pytest-cov
        - vcrpy
        - httpx
      commands:
        - pip check
        - gql-cli --help
        - gql-cli --version
        - gql
        - gql.transport.httpx
        - gql.transport.aiohttp
        - gql.transport.requests
        - gql.transport.appsync_auth
        - gql.transport.websockets
        - pytest tests -vv  # [not win]
        # test is inconsistent and times out on CI
        - pytest tests -vv -k "(not test_graphqlws_subscription_reconnecting_session)"  # [win]
about:
  home: https://github.com/graphql-python/gql
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: GraphQL client for Python
  description: |
    This is a GraphQL client for Python. Plays nicely with graphene,
    graphql-core, graphql-js and any other GraphQL implementation compatible
    with the spec.
  doc_url: https://gql.readthedocs.io/
  dev_url: https://github.com/graphql-python/gql
extra:
  feedstock-name: gql
  recipe-maintainers:
    - leszekhanusz
    - ozagordi
    - KingDarBoja
    - bollwyvl
