{% set version = "3.5.0" %}

package:
  name: gql-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gql/gql-{{ version }}.tar.gz
  sha256: ccb9c5db543682b28f577069950488218ed65d4ac70bb03b6929aaadaf636de9

build:
  number: 0
  skip: true  # [py<36 or s390x]

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  commands:
    - echo "tests in outputs"

outputs:
  - name: gql
    build:
      script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
      entry_points:
        - gql-cli=gql.cli:gql_cli
    requirements:
      host:
        - python
        - pip
        - wheel
      run:
        - python
        - graphql-core >=3.2,<3.3
        - yarl >=1.6,<2.0
        - backoff >=1.11.1,<3.0
        - anyio >=3.0
      run_constrained:
        # aiohttp
        - aiohttp >=3.7.1
        # requests
        - requests >=2.26,<3
        - requests-toolbelt >=0.9.1,<1
        - urllib3 >=1.26
        # websockets
        - websockets >=10,<11
        # boto
        - botocore >=1.21,<2
    test:
      imports:
        - gql
      requires:
        - pip
      commands:
        - pip check
        - gql-cli --help
        - gql-cli --version

  - name: gql-with-aiohttp
    build:
    requirements:
      host:
        - python
        - pip
        - wheel
      run:
        - {{ pin_subpackage('gql', exact=True) }}
        - aiohttp
        - python
    test:
      imports:
        - gql
        - gql.transport.aiohttp
      requires:
        - pip
      commands:
        - pip check
        - gql-cli --help
        - gql-cli --version
    about:
      summary: GraphQL client for Python - aiohttp transport

  - name: gql-with-requests
    build:
    requirements:
      host:
        - python
        - pip
      run:
        - {{ pin_subpackage('gql', exact=True) }}
        - python
        - requests
        - requests-toolbelt
        - urllib3
    test:
      imports:
        - gql
        - gql.transport.requests
      requires:
        - pip
      commands:
        - pip check
        - gql-cli --help
        - gql-cli --version
    about:
      summary: GraphQL client for Python - requests transport

  - name: gql-with-websockets
    build:
    requirements:
      host:
        - python
        - pip
        - wheel
      run:
        - {{ pin_subpackage('gql', exact=True) }}
        - python
        - websockets
    test:
      imports:
        - gql
        - gql.transport.websockets
      requires:
        - pip
      commands:
        - pip check
        - gql-cli --help
        - gql-cli --version
    about:
      summary: GraphQL client for Python - websocket transport

  - name: gql-with-botocore
    build:
    requirements:
      host:
        - python
        - pip
      run:
        - {{ pin_subpackage('gql', exact=True) }}
        - botocore
        - python
    test:
      imports:
        - gql
        - gql.transport.appsync_auth
      requires:
        - pip
      commands:
        - pip check
        - gql-cli --help
        - gql-cli --version
    about:
      summary: GraphQL client for Python - boto transport

  - name: gql-with-all
    build:
    requirements:
      host:
        - python
        - pip
        - wheel
      run:
        - {{ pin_subpackage('gql-with-aiohttp', exact=True) }}
        - {{ pin_subpackage('gql-with-botocore', exact=True) }}
        - {{ pin_subpackage('gql-with-requests', exact=True) }}
        - {{ pin_subpackage('gql-with-websockets', exact=True) }}
        - {{ pin_subpackage('gql', exact=True) }}
        - python
    test:
      source_files:
        - tests
      requires:
        - aiofiles
        - mock
        - parse
        - pip
        - pytest
        - pytest-asyncio
        - pytest-console-scripts
        - pytest-cov
        - vcrpy
        - httpx
      commands:
        - pip check
        - gql-cli --help
        - gql-cli --version
        - pytest tests -vv
about:
  home: https://github.com/graphql-python/gql
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: GraphQL client for Python
  description: |
    This is a GraphQL client for Python. Plays nicely with graphene,
    graphql-core, graphql-js and any other GraphQL implementation compatible
    with the spec.
  docs_url: https://gql.readthedocs.io/en/stable/
  dev_url: https://github.com/graphql-python/gql
extra:
  feedstock-name: gql
  recipe-maintainers:
    - leszekhanusz
    - ozagordi
    - KingDarBoja
    - bollwyvl
