travis:
  secure:
    BINSTAR_TOKEN: HnP3I0w5A5zPUS4ifue3GQAvD7eOCBXzxOJt4b5nBhfprmN5YB8yz81E1SUd3U7J8O+mipCFHfT4xSIhLXbkgxom95g+RTv4MVBbAVbchSKJcHODCzfTIO4ZKEzyA2zmi5mS5wpiOVmWn+uZt6wXC30EgN8av6Abg5jOwSPQpTqxZjYeoOWBspq3VtuFM4XquDytmYFEt/RpO5420f/PnviHI+5AAGCmuS16zrLj6bG4wPruqMTqqgk1dlTPU3+SDnFEBAHd12IRB4rAl2KfQi1LeMePTUArkT7yKkQpKcGQ+DpF8x7YVQMF1dF7Knx1XtETzYinHagoA9bAH3+apSW95vKkUl8xKcU9BjLTjwdU5hLcpenCTjxAD7noIoHfJn7beWA4FkvmQPQzDtX56EB3NTnnBUn+/AIxmFKxVqmtKpO0Y6VozsPkPBPyhv5rDr9iLXzwHuaLEhQeeBgtC2q+zdsbZqpCZxa4LkzQc5Vgtd91uA6laJaq8OsrJEVhrzoPPeGTj9iqvbwMd2A2fTXjmtX7itfGFnpoQ23d+1jescWVXNZMR3zeAONw7f0p6cgzRSxmQyTfd6kRtQO5e2s3D0yGiz20xGX27BJFLVRuSfKwyG5zX7J9hMRC0gfw/y5ANZVe88inehSaLi7w9ea5NP1JPqLKOyzwZIqMOew=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
