travis:
  secure:
    BINSTAR_TOKEN: DtuKcZJO9J3pUMCGwXPonhek3brYLKSDx3fyapT1zNNcL2j9gZ9dud/dTFsFDjzaGGieG/WPKCr6DT5ad1scojMuHTXT+VvESMMOHdNYOggi8LeW0ZLvs9FyVH4Nyq2DwYKbuitbGtZH6Vs7tayS2l1lXDYQQf2pDKiIYWlfPPoH00ksDr1rcx8A/3vVadbRXmox/Xg1ZOk1RhXsM7JMvu+L4+N610pMXS+xmFs/KxMEde+8eKcYaa4AqEVX/L/mMaFSsgfHYW5aoUXhX9FfdJV8YX1kHzkbM81EqhYRl5g2q9VHFnJYceeUpFgN6t4KBj8DIr+BYq6NN4MxFgbsMW7YQWk/frxCcmkW82kxfW5CxY4l5WceztsQUAhxqT09655hSv+/JhQzltLj6kMoTyqKMEgE7NSa4P1Q8vZWyz2elmDdszLmOr2BuJ8I4uJx5rtuqaC1xGSNLAj2jc292zKzQCpD9FH9PBXHzD8+z88725iwempH/eaM2ABs5ie2y63nODwAIONe1NMEwtKo85VM3hyVXBNPlF0ZK0qrJ+BJxFYClWtIByl2dQUpBVHvB6U1Sg1cJPj4k9GxZ4XHrYvt4BTMi7fBJnV7yPFgKyicSng99Vz7drrkKN5eLzVtirlOuZv72auDQSE1z0tHsgqKPmWlKe2r4fnz9jd+1TI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
