travis:
  secure:
    BINSTAR_TOKEN: nPDtum6h7dOY82wfeG2OAhePk7wTfb5L4i1TuwDfs0CtxKlAfbDr6uwtYIg6gHUh5PsitHc9hFa9Tun83kBXYXLyen9qHbbSCgIxT4//eVeTv0UXx4P9jTSq1jLWKaf0og4cjd2XdFdEwmGJZD5V7bE/7Of8wgBPluMNmaTZBqTFotYc8K3kbe/MiDEz4EfxMRUX8RYrvyn73oPTznhIGwWrcKKqWaCcLIAXLv0C17EeOTUdLrTY9kM81QD2sk9LKELiRaK2LLPOLN9r/4QbqK+k2SmNcsuncTh/awkfUxjTZ8vhIN1kW8A/GcBVeHTJWXLfeykOHErGMc5iISxSsF4EYcYn2/saqwRJ8O4k3rgclgUgO9I7HuZquQ95rBEmECZIDWUyPjkNU3JZ9zUbxBgatX1xXB55AT3mPcjoidCmaubPYYuzLVmMOK6fzGS1UBrMLHUIvF4l6qcCEN1XwCQbjgQRm3RFy1l7ksVH+MFUY5+/xA2orohuJnVeBX9UDYzRN4nrpFhx0/vTIxBawXGy2mHq7juRFHvxraapZwHAd107qD5n+/tLUzImuLQuatY9ED4Gg8SiFMH/q+cdKz0rQPzX+2hSIukB7pm/0kLMFyICGWBP6nfiHi7mEH2Ub3yeuKE8S57BPoKWrtOlE1+C8tq9S+jd64s007siAJo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
